#!/bin/bash

(return 0 2>/dev/null) && sourced=1 || sourced=0

if [ $sourced -eq 0 ]
then
    echo Usage: source setenv
    echo
    echo Sets the environment for open frameworks
    exit 1
fi

echo Setting OF_ROOT
export OF_ROOT=$(find ~/dev -maxdepth 1 -name of*)
echo OF_ROOT: $OF_ROOT
echo

echo 'source ~/dev/emsdk/emsdk_env.sh'
source ~/dev/emsdk/emsdk_env.sh

